
### Lets create a neural network:

> 4 inputs, connected to 3 neurons in a layer.

* ***neuron1*** is the summation of the inputs * the weights, with bias1 added

* ***neuron2*** is the summation of the inputs * the weights, with bias2 added

* ***neuron3*** is the summation of the inputs * the weights, with bias3 added

> this is a ***fully connected network***    
    

In [2]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    #neuron1 = inputs * weights
    inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    
    #neuron2 = inputs * weights
    inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,

    #neuron3 = inputs * weights
    inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3,
]

print(outputs)


[4.8, 1.21, 2.385]


lets simplify this code to be more readable and handle dynamically-sized inputs and layers:

> this uses a for loop to interate through the weights and biases for each of the neuron

* within that for loop, it uses another loop to iterate through the inputs and the corresponding weights for each neuron

> it calculates the output for each neuron by doing sum(inputs[i] * weights[i]) + bias, appending to output layer list.

In [3]:
inputs = [1, 2, 3, 2.5]

weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]

biases = [2, 3, 0.5]

#output of the current layer:
layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    print(neuron_weights, neuron_bias)
    #zeroed output of given neuron
    neuron_output =  0
    #for each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        #multiply this input by the associated weight, add bias, add to the neuron's output variable
        neuron_output += n_input*weight
    # add bias to this neuron output
    neuron_output += neuron_bias    
    #put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)

print('Outputs: ', layer_outputs)        

[0.2, 0.8, -0.5, 1] 2
[0.5, -0.91, 0.26, -0.5] 3
[-0.26, -0.27, 0.17, 0.87] 0.5
Outputs:  [4.8, 1.21, 2.385]


### Tensors, Arrays, and Vectors

> What are ***tensors***?

* A tensor, fundamentally, is an object that can be represented as an array

> So what are ***arrays***?

* An array is an ordered, homologous container for numbers. Can be multi-dimensional.

    this represents a 2D array, of shape (3, 2), as it contains 3 rows of 2 columns:

            list_matrix_array = [
                [3, 2],
                [5, 1],
                [8, 2]]

    this represents a 3-dimensional array, with 3rd level of brackets:

            lolol = [[[1,5,6,2],
                    [3,2,1,3]],
                    [[5,2,1,2],
                    [6,4,8,4]],
                    [[2,8,5,3],
                    [1,1,9,4]]]

    the first level of the array contains 3 matrices, thus size at this level is of dimension 3.

        [[1,5,6,2], [3,2,1,3]]
        [[5,2,1,2], [6,4,8,4]]
        [[2,8,5,3], [1,1,9,4]]

    in the first matrix, it contains 2 lists, thus size at this level is of dimension 2.

        [1,5,6,2] and [3,2,1,3]

    within the first matrix's list, aformentioned list contains 4 elements, thus size at this level is of dimension 4.    

        len([1,5,6,2]) = 4

    so the shape of this 3D array is (3, 2, 4)

    A ***vector*** is simply a 1-dimensional array, (list is python).     
        
        vector = [1,2,3]

    A 2d array which consists of 1 row of X columns:

        2d_array = [[1,2,3]] 

    The shape of *vector* is (3,), which means that it is a vector (1d array) of 3 elements. On the other hand, 2d_array has a shape of (1, 3), which means that it is a matrix that consists of 2 row and 3 columns (elements)

    The difference between the two is that since vector is simply a vector (list), it does not have any row and columms (no orientation), which means that it can be represented as a row or column vector (no transposing necessary). 2d_array is a matrix, so it can be indexed by rows and columns.


### Dot Product and Vector Addition

 a ***Dot Product*** is multiplying each element in our inputs and weight vectors element-wise. (Matrix multiplication)

* this is a cleaner way to perform the necessary calculations.

* the result of the dot product is a scalar value.


$ a \cdot b = \sum_{i=1}^{n}(a_ib_i) = a_1b_1 + a_2b_2 +...+ a_nB_n $
 * this represents the sum of products of consecxutive vector elements.

 > The dot product only works when : same number of columns of first matrix and same number of rows in the second matrix.

In [4]:
a = [1,2,3]
b = [2,3,4]

#to obtain the dot product:
dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


 the above code is prepresented in mathemetical form as:

$ a \cdot b = [1,2,3] * [2,3,4] = 1 * 2 + 2 * 3 + 3 * 4 = 20 $

***Vector Addition*** is the combination of two two or more vectors to create a new vector

* operation is performed element-wise.

$ A + B = [A_1 + B_1, A_2 + B_2, ..., A_n + B_n] $


### Single Neuron with Numpy

Lets code the neuron using the dot product and the addition of vectors in numpy now:

* makes the code much simpler to read.

In [5]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = [2.0]

outputs = np.dot(weights, inputs) + bias
print(outputs)

[4.8]


Lets now create the code for a network with a layer of three neuron, like the example in the previous code.

* for np.dot, it multiplies each of the list of weights with the inputs respectively, so that np.dot can be expanded to:

        np.dot(weights, inputs) = [np.dot(weights[0], inputs), np,dot(weights[1], inputs), np.dot(weights[2], inputs)

* whatever comes first in np.dot will decide the output shape. In this case, we are passing a list of neuron weights first, then the inputs, as our goal is to get the list of neuron outputs.        

* the dot product of a matrix and a vector always results as a list of dot products

        A = [[a11,a12,a13],
        [a21,a22,a23],
        [a31,a32,a33]]
        
        x = [x1,x2,x3]

        A.x = [np.dot(A[0], x), np.dot(A[1], x), np.dot(A[2], x)]        

In [6]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = [np.dot(weights, inputs) + biases]

print(layer_outputs)

[array([4.8  , 1.21 , 2.385])]


### A Batch of Data

To train, neural networks ten to receive data in ***batches***

> it is faster to train in batches in parallel processing, and it helps with the generalization during training.

* if you fit one one sample at a time, you are more than likely fitting to that individual sample rather than the whole dataset.

* each element in the batch is the ***sample***, also referred to as the ***feature set of instances*** or ***observations***

In [7]:
#Example of a batch of data:
batch = [[1,5,6,2],[3,2,1,3],[5,2,1,2],[6,4,8,4]] #shape: (4,4),

### Matrix Product

the ***Matrix Product*** is an operation in which you have two matrices, and you are performing the dot product of all the combinations of rows from the first matrix and the columns of the second matrix, resulting in the dot product matrix of the two original matrices.

To perform a matrix product:

* size of the second dimension of the left matrix must match the size of the first dimension of the right matrix:

    > left matrix: shape = (5,4), right matrix: shape = (4,7), thus the left matrix's column matches the right matrix's row, thus dot product can occur.    

    > resultant matrix: (first dimension of first matrix, second dimension of second matrix): shape = (5, 7)

### Transposition for the Matrix Product

recall, a dot product of two vectors equates to the matrix product of a row vector and column vector.

***Transposition*** modifies a matrix in a way that its rows becomes its columns and its columns become its rows.

$ a * b = a * b^{T} $, where $ b^{T} $ is the Transposition of b.

$ \begin{bmatrix} a & b & c \end{bmatrix}^{T} = \begin{bmatrix} a \\ b \\ c \end{bmatrix}  $

> a n X m matrix becomes a m X n matrix.

$ \begin{bmatrix} 1 & 2 & 3 \end{bmatrix} * \begin{bmatrix} 2 \\ 3 \\ 4 \end{bmatrix} = [20] $


In [8]:
#this is a vector (1 dimensional array)
np.array([1,2,3])

array([1, 2, 3])

In [16]:
#this is a two-dimensional array (row vector), shape is (1, 3)
a = [1,2,3]
a = np.expand_dims(np.array(a), axis=0)
print(a, a.shape)

[[1 2 3]] (1, 3)


In [19]:
#this is a two-dimensional array (column vector), shape is (3, 1)
b = [2,3,4]
b = np.array([b])
print(b, b.shape)
b = b.T
print(b, b.shape)

[[2 3 4]] (1, 3)
[[2]
 [3]
 [4]] (3, 1)


In [22]:
#lets now perform the dot product of the two (matrix product since both a and b are now 2 dimensional arrays)
c = np.dot(a, b)
print(c, c.shape)

[[20]] (1, 1)


### A Layer of Neurons & Batch of Data w/ NumPy

As seen previously, we were able to perform the dot product on the inputs and the weights without a transposition because the weights were a matrix, but the inputs were only a vector (n, ). In this case, the dot product results in a vector of dot products performed on each row from the matrix and this single vector.

When inputs become a batch of inputs (matrix), we must perform matrix product, which takes all the combinations of rows from the first matrix and columns from the right matrix, perfroming the dot product on them and placing the results in an output array.

$
     \begin{bmatrix}
         0 & 1\\ 
         0 & 0 
     \end{bmatrix}
     \times
     \begin{bmatrix}
         0 & 0\\ 
         1 & 0  
     \end{bmatrix}
      =
     \begin{bmatrix}
         1 & 0\\ 
         0 & 0   
     \end{bmatrix}
  $

  Remember, to perform the matrix product, **second dimension from first matrix must match the first dimension of the second matrix!**

if a = (3, 4), b = (3, 4), you cannot perform the matrix product of this!

transpose b so that b = (4, 3),

then, 

(3, 4) * (4, 3) = (3, 3) matrix!

In [41]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]
         ]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]
          ]

biases = [2.0, 3.0, 0.5]

#lets change both of these 2 dimensional lists into numpy arrays,
inputs = np.array(inputs)
weights = np.array(weights)

#lets show the shape of both: (3, 4) matrices,
print('inputs shape:', inputs.shape, 'weights shape:', weights.shape, '\n')

#finally, lets do the matrix product of the inputs and the weights. Remember that one of the matrices has 
#to eb transposed so that the matrix product can be computed correctly.
outputs = np.dot(inputs, weights.T) + biases

print('outputs: \n', outputs, '\noutputs shape:', outputs.shape)


inputs shape: (3, 4) weights shape: (3, 4) 

outputs: 
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]] 
outputs shape: (3, 3)


unlike the code previously where weights were the first parameter in np.dot(), this time inputs is the frist parameter. This is because the resultant array is sample based and not neuron based. the next layer would expect a batch of inputs and the dot product operation will provide a list of layer outputs per each sample.

*the dot product of each sampel (row) in the inputs array is calculated with the same set of weights. The reuslt in a list of outputs, one for each sample, that represents the output of the layer for each sample.

the biases vector will be added to each row vector of the matrix.

In [42]:
x = [(1.0*0.2) + (2.0*0.8) + (3.0*-0.5) + (2.5*1.0)]
print(x)

[2.8]
