### Backpropagation

by calculating the gradients, which is the vector of all possible partial derivatives of a functiion with respect to all of its respective parameters, we can do the chain rule, which is the derivative of the chained functions, which are the product of the partial derivatives with respect to the loss

lets demonstrate the backpropagation by computing it at the ReLU activation output layer first. We will then do this for the loss function:

In [2]:
import math
#the input values, its weights, and the bias
x = [1.0, -2.0, 3.0]
w = [-3.0, -1.0, 2.0]
b = 1.0

above shows 2 vectors: the inputs and weights, and the bias.

as you can see, the number of neurons for the subsequent layer will be 1, given that there is only one sample for x, and one set of weights for the inputs.

(n_samples, num_features) * (num_features, n_neurons) = (n_samples, n_neurons)

(1, 3) * (3, 1) = (1, 1), so single value for the output

In [3]:
input_weights = [x*w for x, w in zip(x, w)]
print(input_weights)

[-3.0, 2.0, 6.0]


input_weights represent the input and weight muliplication operation, multiplying each element in x with each element in w element-wise.

z represents the sum of input_weights, plus the bias

y represents the reLU activation function, which returns z if z > o, otherwise 0

In [7]:
z = sum(input_weights) + b
print('output before reLU activation function:', z)

y = max(z, 0)
print('output after the reLU activation function: ', y)

output before reLU activation function: 6.0
output after the reLU activation function:  6.0


now, lets compute the gradients:

first, we must compute the derivative of the reLU function.

> the derivative of reLU() with respect to its input z is:

* 1 if z > 0, otherwise 0.

we must take the derivative (gradient) from the next layer, in this case we will make up this value for demonstration purposes


In [8]:
#derivative from the next layer
dvalue = 1.0

#derivative of ReLU and the chain rule, which is gradient of the next
#layer multiplied by the derivative of the current layer
drelu_dz = dvalue * (1 if z > 0 else 0)

print('the derivative of the next layer is: ', dvalue)
print('the derivative of the current layer: ', (1 if z > 0 else 0))
print('the chain rule of the next layer with the current: ', drelu_dz)

the derivative of the next layer is:  1.0
the derivative of the current layer:  1
the chain rule of the next layer with the current:  1.0


next, we have to calculate the partial derivative of the sum function, then use the chain rule to multiply this with the partial derivative of the reLU partial derivative.

results will be:

> drelu_dwx0: the partial derivative of the ReLU wrt. the first weighted input, w0x0

> drelu_dwx1: the partial derivative of the ReLU wrt. the second weighted input, w1x1

> drelu_dwx2: the partial derivative of the ReLU wrt. the third weighted input, w2x2

> drelu_db: the partial derivative of the ReLU wrt. the bias, b

the partial derivative of the sum operation is always 1, no matter the inputs.

$ f(x, y) = x + y $

partial derivative of the function with respect to x:
$ \frac{\partial}{\partial_x}f(x,y) = 1 $

partial derivative of the function with respect to y:
$ \frac{\partial}{\partial_y}f(x,y) = 1 $

thus, the partial derivative of the sum with respect to each of its input*weights are:

> dsum_dxw0: 1

> dsum_dxw1: 1

> dsum_dxw2: 1

> dsum_db: 1

from here, we do the chain rule to find the derivative of the reLU with respect to each of the input*weights:


In [11]:
#partial derivatives of the sum function wrt each of the weighted inputs,
#and the bias. the sum operation is always 1
dsum_dxw0 = 1
dsum_dxw1 = 1
dsum_dxw2 = 1
dsum_db = 1

#using chain rule so that we know the partial derivatives of the reLU
#function with respect to each of the weighted inputs. 
drelu_dwx0 = dsum_dxw0 * drelu_dz
drelu_dwx1 = dsum_dxw1 * drelu_dz
drelu_dwx2 = dsum_dxw2 * drelu_dz
drelu_db = dsum_db * drelu_dz

print('partial derivative of the sum function wrt. weighted inputs0: ', dsum_dxw0)
print('partial derivative of the sum function wrt. the weighted inputs1', dsum_dxw1)
print('partial derivative of the sum function wrt the weighted inputs2: ', dsum_dxw2)
print('partial derivative of the sum function wrt the bias: ', dsum_db)

print('partial derivative of the reLU function wrt the weighted inputs0', drelu_dwx0)
print('partial derivative of the reLU function wrt the weighted inputs1', drelu_dwx1)
print('partial derivative of the reLU function wrt the weighted inputs2', drelu_dwx2)
print('partial derivative of the reLU function wrt the bias', drelu_db)

partial derivative of the sum function wrt. weighted inputs0:  1
partial derivative of the sum function wrt. the weighted inputs1 1
partial derivative of the sum function wrt the weighted inputs2:  1
partial derivative of the sum function wrt the bias:  1
partial derivative of the reLU function wrt the weighted inputs0 1.0
partial derivative of the reLU function wrt the weighted inputs1 1.0
partial derivative of the reLU function wrt the weighted inputs2 1.0
partial derivative of the reLU function wrt the bias 1.0


now, we must find the find the partial derivative of the multiplication function, then use the chain rule again.

the partial derivative of the multiplicaiton function is whatever the input is being multiplied by. for example:

$ f(x, y) = x * y $

partial derivative of the function with respect to x:
$ \frac{\partial}{\partial_x}f(x,y) = y $

partial derivative of the function with respect to y:
$ \frac{\partial}{\partial_y}f(x,y) = x $

thus, the partial derivative of the first weighted inputs with respect to the input is the weight

then, we apply chain rule and multiply this partial with the partial of the subsequent function.

In [18]:
#partial derivatives of the multiplication function wrt. each of the inputs:
dmul_dx0 = w[0]
dmul_dx1 = w[1]
dmul_dx2 = w[2]

#you do not need to do the partial derivative of the bias, because it isnt being multiplied.
print('partial derivative of the multiplication function wrt x0: ', dmul_dx0)
print('partial derivative of the multiplication function wrt x1: ', dmul_dx1)
print('partial derivative of the multiplication function wrt x2: ', dmul_dx2, '\n')


#now, do chain rule of these derivatives with the subsequent one we did previously
drelu_dx0 = drelu_dwx0 * dmul_dx0
drelu_dx1 = drelu_dwx1 * dmul_dx1
drelu_dx2 = drelu_dwx2 * dmul_dx2

#partial derivatives of the multiplication function wrt. each of the weights:
dmul_dw0 = x[0]
dmul_dw1 = x[1]
dmul_dw2 = x[2]

print('partial derivative of the multiplication function wrt w0: ', dmul_dw0)
print('partial derivative of the multiplication function wrt w1: ', dmul_dw1)
print('partial derivative of the multiplication function wrt x2: ', dmul_dx2, '\n')

#now, do chain rule of these derivatives with subsequent one we did preiously
drelu_dw0 = drelu_dwx0 * dmul_dw0
drelu_dw1 = drelu_dwx0 * dmul_dw1
drelu_dw2 = drelu_dwx0 * dmul_dw2

print('partial derivative of the reLU function with resepct to the input 0: ', drelu_dx0)
print('partial derivative of the reLU function with resepct to the weight 0: ', drelu_dw0)
print('partial derivative of the reLU function with resepct to the input 1: ', drelu_dx1)
print('partial derivative of the reLU function with resepct to the weight 1: ', drelu_dw1)
print('partial derivative of the reLU function with resepct to the input 2: ', drelu_dx2)
print('partial derivative of the reLU function with resepct to the weight 2: ', drelu_dw2)

print('partial derivatve of the reLU function with respect to the bias: ', drelu_db)

partial derivative of the multiplication function wrt x0:  -3.0
partial derivative of the multiplication function wrt x1:  -1.0
partial derivative of the multiplication function wrt x2:  2.0 

partial derivative of the multiplication function wrt w0:  1.0
partial derivative of the multiplication function wrt w1:  -2.0
partial derivative of the multiplication function wrt x2:  2.0 

partial derivative of the reLU function with resepct to the input 0:  -3.0
partial derivative of the reLU function with resepct to the weight 0:  1.0
partial derivative of the reLU function with resepct to the input 1:  -1.0
partial derivative of the reLU function with resepct to the weight 1:  -2.0
partial derivative of the reLU function with resepct to the input 2:  2.0
partial derivative of the reLU function with resepct to the weight 2:  3.0
partial derivatve of the reLU function with respect to the bias:  1.0


now, we will uses these partial derivatives, (which is the gradient), to the weights to minimize the output. this is referred to as the optimizer

in this case, we will apply a negative fraction to the gradients of the weights, since we want to decrease the final output value.

lets show the current values of the weights and the bias:

In [20]:
print(w, b)

[-3.0, -1.0, 2.0] 1.0


let now modify the weight values using the gradients of each respective weights:

> changed the weights and biases slightly as to decrease the output.

In [23]:
dx = [drelu_dx0, drelu_dx1, drelu_dx2]
dw = [drelu_dw0, drelu_dw1, drelu_dw2]
db = drelu_db

w[0] += -0.001 * dw[0]
w[1] += -0.001 * dw[1]
w[2] += -0.001 * dw[2]
b += -0.001 * db

print(w, b)

[-3.0029999999999997, -0.994, 1.9910000000000003] 0.998


lets do another forward pass and see the changes:

In [24]:
#multiplying the inputs and weights
input_weights = [x*w for x, w in zip(x, w)]
print(input_weights)

[-3.0029999999999997, 1.988, 5.973000000000001]


In [25]:
#adding (performing the dot product, adding the bias)
z = sum(input_weights) + b
print('output before the reLU activation function: ', z)

#reLU activation function
y = max(z, 0)
print('output after the reLU activation function: ', y)

output before the reLU activation function:  5.956000000000001
output after the reLU activation function:  5.956000000000001


As you can see from the above code, we have minimized the reLU output. In a real world application, we do not minimize this layer, but rather the loss function. Remember we only did this for the reLU for demonstation purposes.

#### Backprop with multiple neurons

now, instead of a single neuron, we have a layer with multiple neurons. During backprop, wach neuron from the current layer will recieve a vector of partial deriviatives instead of a sinlge value. 

below is the code to show this: 

> take the transposed weights, which are the transposed aray of the derivatives wrt the inputs, and multiply them by their respective gradients (related to the given neurons) to apply the chain rule.

> then, we sum along with the inputs.

> calculate the gradient for the next layer in the backpropogation. the next layer is the previous layer in the order of creation of the model.

In [48]:
import numpy as np

#passed in gradient from the next layer. use vector of 1s for this example
#remember, this will have to be a 2D array of rows and columns.
dvalues = np.array([1., 1., 1.])
print('gradients from the next layer: ', dvalues)
print('dvalue shape: ', dvalues.shape)

gradients from the next layer:  [1. 1. 1.]
dvalue shape:  (3,)


In [33]:
#we have 3 sets of weights, one set for each neuron. 4 inputs, thus 4 weights.
weights = np.array([[0.2, 0.8, -0.5, 1], [0.5, 10.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])
print('this is the weights: \n', weights)
print('this is the weight''s shape', weights.shape)
weights_T = weights.T
print('this is the weights transposed: \n', weights_T)
print('this is now the weight''s shape: ', weights_T.shape)

this is the weights: 
 [[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  10.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]]
this is the weights shape (3, 4)
this is the weights transposed: 
 [[ 0.2   0.5  -0.26]
 [ 0.8  10.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]
this is now the weights shape:  (4, 3)


In [49]:
#sum weights of the given input. multiply the passed in gradient for this neuron
dx0 = sum(weights_T[0]) * dvalues[0]
dx1 = sum(weights_T[1]) * dvalues[0]
dx2 = sum(weights_T[2]) * dvalues[0]
dx3 = sum(weights_T[3]) * dvalues[0]

#gradient of the neuron's function wrt the inputs
dinputs = np.array([dx0, dx1, dx2, dx3])
print(dinputs)

[ 0.44 11.44 -0.07  1.37]


the sum of the multiplicaiton of the elements is the dot product. we can achieve same by doing np.dot

In [59]:
import numpy as np

dvalues = np.array([1,1,1])
print(dvalues.shape)

weights = np.array([[0.2, 0.8, -0.5, 1], [0.5, 10.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])

#sum weights of the given inputs, multiply the passed in each gradient for this neuron
dinputs = np.dot(dvalues, weights)
print(dinputs)

(3,)
[ 0.44 11.44 -0.07  1.37]


now, lets account for batches of samples. Above, we are using a single sample responsible for a single gradient that is backpropagated between alyers. The row vector that we created for dvalues is in proparation for the batch of data.

with more samples, the layer will return a list of gradients.

In [61]:
import numpy as np

dvalues = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(dvalues.shape)

weights = np.array([[0.2, 0.8, -0.5, 1], [0.5, 10.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])

dinputs = np.dot(dvalues, weights)
print(dinputs)

(3, 3)
[[ 0.44 11.44 -0.07  1.37]
 [ 0.88 22.88 -0.14  2.74]
 [ 1.32 34.32 -0.21  4.11]]


lets combine the forward and backward pass of a single neuron with a full layer and batched-based partial derivatives. We'll minimize ReLU's output, once again, for this example only

In [71]:
import numpy as np

#passed in gradient from the next layer, array of incremental gradient values
dvalues = np.array([[1,1,1],[2,2,2],[3,3,3]])

#we have 3 sets of inputs - samples
inputs =  np.array([[1, 2, 3, 2.5],
                    [2., 5., -1., 2],
                    [-1.5, 2.7, 3.3, -0.8]])

print('input shape: ', inputs.shape)

'''we have 3 sets of weights - one set for each neuron,
   we have 4 inputs, thus 4 weights for each neuron'''
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

print('weights shape: ', weights.shape)

#one bias for each neuron, biases are just a row vector of the shape (1, num_neurons)
biases = np.array([[2,3,0.5]])

#forward pass: perform the dot product, then perform the reLU activation function
layer_outputs = np.dot(inputs, weights) + biases
print('layer outputs before reLU activation function: \n', layer_outputs)
relu_outputs = np.maximum(0, layer_outputs)
print('layer outputs after the reLU activation function: \n', relu_outputs)

'''lets optimize and test the backpropagation.
    ReLU activation simulates derivative wrt the input values from the next layer
    passed to the current layer during backpropagation
'''
drelu = relu_outputs.copy()
drelu[layer_outputs <= 0] = 0
print(drelu)

#Dense layer: 
#dinputs - multiply by weights
dinputs = np.dot(drelu, weights.T)
#dweights - multiply by inputs
dweights = np.dot(inputs.T, drelu)
#dbiases - sum values, do this over the samples (first axis), keepdims.
dbiases = np.sum(drelu, axis=0, keepdims=True)

#update parameters
weights += -0.001 * dweights
biases += -0.001 * dbiases

print(weights)
print(biases)

input shape:  (3, 4)
weights shape:  (4, 3)
layer outputs before reLU activation function: 
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
layer outputs after the reLU activation function: 
 [[4.8   1.21  2.385]
 [8.9   0.    0.2  ]
 [1.41  1.051 0.026]]
[[4.8   1.21  2.385]
 [8.9   0.    0.2  ]
 [1.41  1.051 0.026]]
[[ 0.179515   0.5003665 -0.262746 ]
 [ 0.742093  -0.9152577 -0.2758402]
 [-0.510153   0.2529017  0.1629592]
 [ 0.971328  -0.5021842  0.8636583]]
[[1.98489  2.997739 0.497389]]


now, we will update the dense layer and ReLU activation code with a backward method.

In [98]:
class Dense_Layer:
    def __init__(self, num_features, num_neurons):
        self.weights = 0.01 * np.random.randn(num_features, num_neurons)
        self.biases = np.zeros((1, num_neurons))

    #remember, we need to remember what the inputs were, when doing backpropagation
    def forward(self, samples):
        self.outputs = np.dot(samples, self.weights) + self.biases
        self.samples = samples

    #it takes in the gradients from the next layer
    def backward(self, dvalues):
        #gradients on parameters
        self.dweights = np.dot(self.samples.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
        #gradients on values
        self.dinputs = np.dot(dvalues, self.weights.T)

class reLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        self.inputs = inputs

    def backward(self, dvalues):
        #since we need to modify the original variable, lets make a copy of values first
        self.dinputs = dvalues.copy()

        #zero gradient where input values were negative
        self.dinputs[self.inputs <= 0] = 0

X  = np.array([[1, 2, 3, 2.5],
                [2., 5., -1., 2],
                [-1.5, 2.7, 3.3, -0.8]])

dvalues = np.array([[1,1,1],[2,2,2],[3,3,3]])

dense1 = Dense_Layer(3, 3)

dense1.weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]]).T

dense1.biases = np.array([[2,3,0.5]])

print(f'current weights: {dense1.weights}\ncurrent biases: {dense1.biases}')
dense1.forward(X)
print(f'current sample(s): {dense1.samples}')
print(f'output before reLU activation function: {dense1.outputs}')
activation1 = reLU()
activation1.forward(dense1.outputs)
print(f'output after reLU activation function: {activation1.outputs}')

activation1.backward(dvalues)
print('backward ', activation1.inputs)
print(f'derivative of the reLU: \n{activation1.dinputs}')

dense1.backward(dvalues)
print(f'current weights: {dense1.dweights}\ncurrent bias: {dense1.dbiases}\ncurrent inputs: {dense1.dinputs}')
        

current weights: [[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]
current biases: [[2.  3.  0.5]]
current sample(s): [[ 1.   2.   3.   2.5]
 [ 2.   5.  -1.   2. ]
 [-1.5  2.7  3.3 -0.8]]
output before reLU activation function: [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
output after reLU activation function: [[4.8   1.21  2.385]
 [8.9   0.    0.2  ]
 [1.41  1.051 0.026]]
backward  [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
derivative of the reLU: 
[[1 1 1]
 [2 0 2]
 [3 3 3]]
current weights: [[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]
current bias: [[6 6 6]]
current inputs: [[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


#### implementation of the Categorical Cross-Entropy Loss derivative code

we want to compute the derivative of the loss function with respect to its inputs, which would be the softmax outputs.

the derivative of the loss function is -(y_true/y_pred).

we will also implement the rest of the code so far for further practice.

to do the derivative of the loss, we must first check how many dimensions the y_true consists o.

if the shape of the labels returns 1, that must mean that it is a one hot vector, thus we need to change it to a list of one hot vectors instead. so we will yse the .eye method from the numpy.

In [2]:
#code explanation of the derivative of the loss.
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

now, let index this table with the numerical label to get the one hot coded vector that it represents. remember, if the y_true is already encoded, we do not need to do this.

In [6]:
print(f'this is the one hot vector for the second row in the array: {np.eye(5)[1]}')
print(f'this is the one hot vector for the fourth row in the array: {np.eye(5)[3]}')

this is the one hot vector for the second row in the array: [0. 1. 0. 0. 0.]
this is the one hot vector for the fourth row in the array: [0. 0. 0. 1. 0.]


In [7]:
import numpy as np

y = [0,1,2,1,0]
y = np.eye(len(y))[y]
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


next, we perform the gradient normalization. divide all of the gradients by the number of samples, so that the gradients are normalized and this makes the sum's magnitude invariant to the number of samples. the sum will be the optimizer. if the gradients arent normalized, when we do the optimization for a large number of samples, we will have the adjust the learning rates according to each set of samples.

In [8]:
import numpy as np

#creation of the dense layer class
class Dense_Layer:
    #initialization of the weights and biases.
    def __init__(self, num_inputs, num_neurons):
        self.weights = 0.01 * np.random.randn(num_inputs, num_neurons)
        self.biases = 0.01 * np.zeros((1, num_neurons))

    #compute the matrix product of the inputs and the weights.
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases
        self.inputs = inputs

    #take gradients of next layer, compute gradients wrt parameters.
    def backward(self, dvalues):
        self.dinputs = np.dot(dvalues, self.weights.T)
        self.dweighhts = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=0, keepdims=True)

#creation of the reLU activation function class.
class reLU:
    #perform the reLU activation function on the outputs.
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        self.inputs = inputs

    #takes gradients from next layer, compute gradients wrt parameters.
    def backward(self, dvalues):
        #if inputs values <=0, set to zero for gradients.
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0

#creation of the softmax activation function class.
class SoftMax:
    #compute the softmax to get the probability distribution of the outputs.
    def forward(self, inputs):
        #normalize the exp values by subtracting max from each row with the row.
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        self.probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

    #derivative of softmax is wrt the inputs is softmax * (1-softmax)
    def backward(self, dvalues):
        pass

#creation of the Categorical Cross Entropy Loss function class.
class CCrossEntropyLoss:
    #compute the loss of the outputs and the true label class.
    def forward(self, outputs, y):
        #clip the data
        outputs_clipped = np.clip(outputs, 1e-7, 1-1e-7)
        #compute the confidence scor es depending on the shape of the true class.
        if len(y.shape)==1: conf =outputs_clipped[range(len(outputs)), y]
        elif len(y.shape)==2: conf = np.sum(outputs*y, axis=1)
        #compute the sample losses and the average losss.
        sample_losses = -np.log(conf)
        average_loss = np.mean(sample_losses)

    #derivative of the loss function wrt its inputs is -(y_true/y_pred).
    def backward(self, dvalues, y):
        #number of samples.
        samples = len(dvalues)
        #number of labels per sample,
        labels = len(dvalues[0])
        #if labels are one dimensional, make them into a one hot vector.
        if len(y.shape)==1: y = np.eye(labels)[y]
        #compute and normalize the gradients
        self.dinputs = -y / dvalues
        self.dinputs = self.dinputs / samples


#### Implementation of the SoftMax activation derivative

now, we want to compute the derivative of the softmax activation wrt its inputs (which will be the outputs from the second dense layer in this case)

the derivative of the softmax is : softmax * (1 - softmax)

lets demonstate this with some example code

In [14]:
import numpy as np

softmax_output =  [0.7, 0.1, 0.2]

softmax_output = np.array(softmax_output).reshape(-1, 1)
print(softmax_output)

[[0.7]
 [0.1]
 [0.2]]


the left side of the equation is softmax's output multiplied by the Kronecker delta

> equals 1 when both inputs are equal

> equals 0 otherwise.

we can visualize this as an array, where its an aray of zeros with the one in the diagonal.

In [15]:
print(np.eye(softmax_output.shape[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


now, we do the multiplication of both of the values from the equation part

In [16]:
print(softmax_output * np.eye(softmax_output.shape[0]))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


we can speed this up by using the np.diagflat method: creates an arrya using an input vector as the diagonal

In [17]:
print(np.diagflat(softmax_output))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


the other part of the equation is the multiplication of the softmax outputs, iterating over the j and k indices respectively. since, for each sample (the i index), we have to multiply the values from the softmax function's output, we can use the dot product operation. for this, we must transpose the second argument to get its row vector form.

In [18]:
print(np.dot(softmax_output, softmax_output.T))

[[0.49 0.07 0.14]
 [0.07 0.01 0.02]
 [0.14 0.02 0.04]]


finally, we can perform the subtraction of both arrays following the equation

In [19]:
print(np.diagflat(softmax_output) - np.dot(softmax_output, softmax_output.T))

[[ 0.21 -0.07 -0.14]
 [-0.07  0.09 -0.02]
 [-0.14 -0.02  0.16]]


the matrix result of the equation and the array solution provided by the code is call the jacobian matrix. in our case, this matrix is an array of partial derivatives in all of the combinations of both input vectors. 

In [20]:
class SoftMax:
    #compute the softmax to get the probability distribution of the outputs.
    def forward(self, inputs):
        #normalize the exp values by subtracting max from each row with the row.
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        self.probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

    #compute the gradients of the softmax wrt the inputs (dvalues).
    def backward(self, dvalues):
        #create an unitialized array.
        self.dinputs = np.empty_like(dvalues)

        #enumerate outputs and gradients.
        for index, (single_output, single_dvalues) in enumerate(zip(self.output, dvalues)):
            #flatten the output array
            single_output = single_output.reshape(-1,1)
            #calculate the jacobian matrix of the output.
            jacobian = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            #calculate the sample-wise gradient and add that to array of sample gradients.
            self.dinputs[index] = np.dot(jacobian, single_dvalues)

in the above code we:

> created an empty array, which will become the resultant gradient array

* this will be the same shape as the gradients that we are recieving to apply the chain rule.

> then we will iterate sample-wise over pairs of the outputs and gradients, calculating the partial derivatives as described ealier and calculating the final product (chain rule) of the jacobian matrix and gradient vector.

* we store the resulting vector as a row in the dinput array.

> we store each vector in each row while iterating, forming the output array.

lets do another example of this using simpler values

In [55]:
import numpy as np

#get the inputs
inputs = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]])
print(f'inputs shape: {inputs.shape}')

#compute the probabilities of each inputs.
exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(f'probabilities:\n {probabilities}\nprobabilities shape: {probabilities.shape}')

#lets assume the gradients of the loss wrt. the probabilities are:
dvalues = np.array([[0.1, 0.2, 0.3, 0.4],
            [0.2, 0.3, 0.4, 0.5],
            [0.3, 0.4, 0.5, 0.6]])

dinputs = np.empty_like(dvalues)

'''for each samples's probabilities and its corresponding dvalues, it:
        -reshape the sample's probabilities to be a row vector. flatten it.
        -compute the jacobian matrix of the sample's probabilities
        -use the jacobian matrix to compute the sample's gradient
            which is the dot product of the jacobian matrix and the 
            corresoponding dvalue
        -add this sample's gradient to the empty sample gradients.
'''
for index, (single_output, single_dvalues) in enumerate(zip(probabilities, dvalues)):
    single_output = single_output.reshape(-1,1)
    print(single_output)
    jacobian = np.diagflat(single_output) - np.dot(single_output, single_output.T)
    sample_gradients = np.dot(jacobian, single_dvalues)
    dinputs[index] = sample_gradients

print(dinputs)



inputs shape: (3, 4)
probabilities:
 [[0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]]
probabilities shape: (3, 4)
[[0.0320586 ]
 [0.08714432]
 [0.23688282]
 [0.64391426]]
[[0.0320586 ]
 [0.08714432]
 [0.23688282]
 [0.64391426]]
[[0.0320586 ]
 [0.08714432]
 [0.23688282]
 [0.64391426]]
[[-0.0079911  -0.01300762 -0.0116701   0.03266881]
 [-0.0079911  -0.01300762 -0.0116701   0.03266881]
 [-0.0079911  -0.01300762 -0.0116701   0.03266881]]


#### Common Categorical Cross Entropy Loss and Softmax activation derivative code

we can simplify the derivative of both of these functions by combining them:

> if we apply the chain rule to both partial derivatives, the whoel equation simplifies significantly to the subtraction of the predicted anf ground truth values. 

> faster to compute

we can create a single class that computes the functions, then do the backward method, which calculates the combined gradient of the loss and activation function

In [56]:
#combining the softmax classifieer and the cross entropy loss for faster compute.
class SoftMaxLossClass:
    #creates the activation and loss function objects.
    def __init__(self):
        self.activation = SoftMax()
        self.loss = CCrossEntropyLoss()

    #forward pass.
    def forward(self, inputs, y):
        self.activation.forward(inputs)
        self.outputs = self.activation.output
        return self.loss.forward(self.outputs, y)
    
    #backward pass.
    def backward(self, dvalues, y):
        #number of samples.
        samples = len(dvalues)
        #if labels are one-hot encoded, turn them to discrete values.
        if len(y.shape)==2: y = np.argmax(y, axis=1)
        #copy the dvalues into gradient inputs
        self.dinput = dvalues.copy()
        #compute the gradient.
        self.dinputs[range(samples), y] -= 1
        #normalize the gradients.
        self.dinputs = self.dinput / samples


### Full Code Implementation

In [61]:
import numpy as np
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import spiral_data

#creation of the dense layer class.
class Dense_Layer:
    #initialization of the weights, biases
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = 0.01 * np.zeros((1, n_neurons))

    def forward(self, inputs):
        #perform the matrix product of the weights and inputs, add biases.
        self.outputs = np.dot(inputs, self.weights) + self.biases
        self.inputs = inputs
    
    def backward(self, dvalues):
        #take gradients from next layer, get gradients wrt. parameters.
        self.dinputs = np.dot(dvalues, self.weights.T)
        self.dweights = np.dot(self.inputs.T, dvalues)
        self.dbiases = np.sum(dvalues, axis=1, keepdims=True)

#creation of the reLU activation function.
class reLU:
    def forward(self, inputs):
        self.outputs = np.maximum(0, inputs)
        self.inputs = inputs

    def backward(self, dvalues):
        #compute gradients of the reLU wrt. gradients from next layer.
        self.dinputs = dvalues.copy()
        self.dinputs[self.inputs <= 0] = 0

#creation of the softmax activation function.
class SoftMax:
    def forward(self, inputs):
        #compute the softmax to ger the probability distribution for each sample.
        exp_values = np.exp(inputs, np.max(inputs, axis=1, keepdims=True))
        self.probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    
    def backward(self, dvalues):
        #computes the gradient of softmax wrt. its inputs.
        #initialize dinputs to be empty array
        self.dinputs = np.empty_like(dvalues)
        for index, (single_output, single_dvalues) in enumerate(zip(self.outputs, dvalues)):
            #change the sample output to be a row vector.
            single_output = single_output.reshape(-1,1)
            #compute the jacobian matrix of the sample output.
            jacobian = np.diagflat(single_output) - np.dot(single_output, single_output.T)
            #calculate the sample-wise gradient, add that to self.dinputs.
            sample_grad = np.dot(jacobian, single_dvalues)
            self.dinputs[index] = sample_grad

#creation of the Categorical Cross Entropy Loss function.
class CCrossEntropyLoss:
    def forward(self, outputs, y):
        #clip the data so no outputs are exactly 0 or 1.
        outputs_clipped = outputs_clipped[outputs, 1e-7, 1-1e-7]
        #confidence scores, depends on shape of the true values.
        if len(y.shape)==1: conf = outputs_clipped[range(len(outputs)), y]
        elif len(y.shape)==2: conf =  np.sum(outputs_clipped* y, axis=1)
        #compute the sample and average losses.
        sample_losses = -np.log(conf)
        average_loss = np.mean(sample_losses)

    def backward(self, dvalues, y):
        #derivative of loss function wrt. its inputs is -(y_true/y_pred)
        samples = len(dvalues)
        labels = len(dvalues[0])
        #if y is not a one hot vector, change it into a one vector.
        if len(y.shape)==1: y = np.eye(labels)[y]
        #compute the gradients.
        self.dinputs = -(y/dvalues)
        #normalize the gradients.
        self.dinputs = self.dinputs / samples

#creation of the combination of the softmax and the ccentropy loss classes.
class SoftMax_Loss_Class:
    def forward(self, inputs, y):
        pass